datacollection/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('dc.urls', namespace='dc')),
]

dc/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.welcome, name='welcome'),

    url(r'^welcome/(?P<user_id>[0-9a-z\-]*)/$', views.welcome, name='welcome_with_id'),
    url(r'^sign_in/$', views.SignInFormView.as_view() , name='sign_in'),
    url(r'^brainstorm/', views.brainstorm, name='brainstorm'),
    url(r'^group/$', views.group_statements, name='group_statements'),
    url(r'^rate/$', views.rate_statements, name='rate_statements'),

    url(r'^thanks/$', views.thanks, name='thanks'),

    url(r'^error/$', views.error, name='error')
]

dc/models.py
from django.db import models
import datetime
import uuid

from django.template.loader import get_template

from django.template import Context

from django.utils.crypto import get_random_string

gender_choices = (
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Other'),
    ('N', "Don't want to answer")
)

main_discipline_choices = (
    ('health', 'Health'),
    ('economy', 'Economy/finance'),
    ('sociology', 'Sociology/social work'),
    ('law', 'Policy and Law'),
    ('other', 'Other')
)

phase_choices = (
    ('newly_added', 'Newly Added'),
    ('brainstorming_completed', 'Brainstorming Completed'),
    ('grouping_enabled', 'Grouping Enabled'),
    ('rating_completed', 'Rating Completed')
)


page_main_url = "http://qba.pythonanywhere.com/"


class Participant(models.Model):
    id = models.CharField(primary_key=True, default=str(uuid.uuid4()), unique=True, editable=False, blank=True, max_length=36)

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_added = models.DateTimeField(default=datetime.datetime.now)

    gender = models.CharField(max_length=1, choices=gender_choices, default='N')
    age = models.IntegerField(default=0)
    age.max_value=150

    position = models.CharField(max_length=100)

    type_experience = models.CharField(max_length=100, blank=True)
    type_experience.verbose_name = "Area of expertise related to exploitation " \
                                   "(for example: precarious, vulnerable, unfree, low-paid or migrant work; " \
                                   "forced labour, modern slavery or human trafficking, ...)"

    discipline = models.CharField(max_length=100, choices=main_discipline_choices, default='other')
    discipline.verbose_name = "Main discipline of expertise"

    other_discipline = models.CharField(max_length=100, blank=True)
    other_discipline.verbose_name = "If Other, please specify:..."

    institution = models.CharField(max_length=100, blank=True)
    institution.verbose_name = "Institution or Organisation"

    country = models.CharField(max_length=200, blank=True)
    country.verbose_name = "Country"

    years_experience = models.IntegerField(blank=True)
    years_experience.verbose_name= "Years of experience in the field related to ‘exploitation’"

    password = models.CharField(max_length=100, default=get_random_string(length=6))

    current_phase = models.CharField(max_length=50, choices=phase_choices, default='newly_added')

    email = models.EmailField()

    def __str__(self):
        return self.full_name()

    def __unicode__(self):
        return self.full_name()

    def user_url(self):
        return page_main_url + "welcome/" + str(self.id) + "/"

    def full_name(self):
        return self.first_name + " " + self.last_name

    user_url.short_description = "User URL"

class ParticipantStatement(models.Model):
    author = models.ForeignKey(Participant)
    timestamp = models.DateTimeField(default=datetime.datetime.now)
    text = models.TextField()

    def __str__(self):
        return self.text

class DistilledStatement(models.Model):
    text_question = models.TextField()

    def __str__(self):
        return self.text_question


class StatementRating(models.Model):
    author = models.ForeignKey(Participant)
    statement = models.ForeignKey(DistilledStatement)
    rating = models.IntegerField()


class StatementSorting(models.Model):
    author = models.ForeignKey(Participant)
    statement = models.ForeignKey(DistilledStatement)
    order = models.IntegerField()
    group_name = models.TextField()


modules = (
    ('home', 'Home'),
    ('brainstorm', 'Brainstorm'),
    ('group', 'Group'),
    ('rate', 'Rate'),
    ('user_email_template', "User Email Template")

)


class ModuleHeading(models.Model):
    module_name = models.CharField(max_length=100, choices=modules)
    heading_content = models.TextField()

    def __str__(self):
        return self.module_name

dc/forms.py
from django import forms

from . import models

from django.forms import formsets


class ParticipantForm(forms.ModelForm):
    class Meta:
        model = models.Participant
        #fields = '__all__' #TODO fix

        fields = [
            'first_name',
            'last_name',
            'gender',
            'age',
            'institution',
            'position',
            'discipline',
            'type_experience',
            'years_experience'
        ]

        widgets = {
            'years_experience': forms.NumberInput(attrs={'min': 0, 'max': 99} ),
            'age': forms.NumberInput(attrs={'min': 18, 'max': 99} ),
        }


class ParticipantStatementForm(forms.Form):
    text = forms.TextInput()


ParticipantStatementFormSet = formsets.formset_factory(ParticipantStatementForm)

dc/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from django.core.urlresolvers import reverse

from django.views import generic
from django.views.generic.edit import *

from django.utils.html import format_html
from .models import *
from .forms import *

import json
import pprint

def welcome(request, user_id=None):
    h = get_object_or_404(ModuleHeading, module_name='home')
    r = {
        'heading': format_html(h.heading_content),
        'user': None
    }

    if request.method == "GET":
        if user_id:
            request.session['attempt_login_id'] = user_id
            p = get_object_or_404(Participant, pk=user_id)
            r['user'] = {
                'first_name': str(p.first_name),
                'id': p.id
            }
        return render(request, 'dc/welcome.html', r)

    elif request.method == "POST":
        if request.POST.get('consent_checkbox'):
            p = get_object_or_404(Participant, pk=request.session.get('attempt_login_id'))

            if not request.POST.get('password') == p.password:
                r['error_message'] = "Incorrect password."
                r['user'] = {
                    'first_name': p.first_name,
                    'id': p.id
                }

                return render(request, 'dc/welcome.html', r)

            request.session['user_id'] = str(p.id)

            if p.current_phase == 'newly_added':
                return HttpResponseRedirect(reverse('dc:sign_in'))
            elif p.current_phase in ('brainstorming_completed', 'rating_completed'):
                return HttpResponseRedirect(reverse('dc:thanks'))
            elif p.current_phase == 'grouping_enabled':
                return HttpResponseRedirect(reverse('dc:group_statements'))
        else:
            print('user didn;t consent')


class SignInFormView(generic.UpdateView):
    model = Participant
    form_class = ParticipantForm
    template_name = 'dc/sign_in.html'
    success_url = '/brainstorm/'

    def get_object(self, queryset=None):
        obj = get_object_or_404(Participant, pk=self.request.session['user_id'])
        return obj

    def get_context_data(self, **kwargs):
        context = super(SignInFormView, self).get_context_data(**kwargs)
        context['user'] = self.object
        return context

    def form_valid(self, form):
        new_participant = form.save()

        return HttpResponseRedirect(self.success_url)


def error(request):
    return render(request, 'dc/error.html')


def brainstorm(request):
    if 'user_id' not in request.session:
        return HttpResponseRedirect(reverse('dc:error'))

    p = get_object_or_404(Participant, pk=request.session['user_id'])

    if request.method == "GET":
        h = get_object_or_404(ModuleHeading, module_name='brainstorm')
        r = {
            'heading': format_html(h.heading_content)
        }

        return render(request, 'dc/brainstorm.html', r)

    elif request.method == "POST":
        statements = request.POST.getlist('statement')
        for s in statements:
            if s:
                db_s = ParticipantStatement(text=s, author=p)
                db_s.save()

        p.current_phase = 'brainstorming_completed'
        p.save()

        return HttpResponseRedirect(reverse('dc:thanks'))


def group_statements(request):
    if 'user_id' not in request.session:
        return HttpResponseRedirect(reverse('dc:error'))

    p = get_object_or_404(Participant, pk=request.session['user_id'])

    if request.method == "GET":
        h = get_object_or_404(ModuleHeading, module_name='group')
        s = DistilledStatement.objects.all()

        r = {
            'heading': format_html(h.heading_content),
            'statements': s
        }
        return render(request, 'dc/group.html', r)

    elif request.method == "POST":
        d = json.loads(request.body.decode("utf-8"))

        group_number = 0

        for group in d:
            for statement in group:
                group_name = statement['group_name']
                s = get_object_or_404(DistilledStatement, pk=statement['id'])

                grouping = StatementSorting(author=p, order=group_number, statement=s, group_name=group_name)
                grouping.save()
            group_number += 1
        return HttpResponseRedirect(reverse('dc:rate_statements'))


def rate_statements(request):
    if 'user_id' not in request.session:
        return HttpResponseRedirect(reverse('dc:error'))

    p = get_object_or_404(Participant, pk=request.session['user_id'])
    s = DistilledStatement.objects.all()

    if request.method == "GET":
        h = get_object_or_404(ModuleHeading, module_name='rate')

        r = {
            'heading': format_html(h.heading_content),
            'statements': s
        }

        return render(request, 'dc/rate.html', r)

    elif request.method == "POST":

        my_dict = dict(request.POST.items())
        pprint.pprint(my_dict)
        #
        # if len(my_dict)-1 < s.count():


        for key, rating in my_dict.items():
            if key == 'csrfmiddlewaretoken':
                continue

            rating = request.POST[key]

            s = get_object_or_404(DistilledStatement, pk=key)

            rating = StatementRating(author=p, statement=s, rating=rating)
            rating.save()


        # for key in request.POST:
        #     print(key + " " + request.POST[key])




        p.current_phase = 'rating_completed'
        p.save()

        return HttpResponseRedirect(reverse('dc:thanks'))


def thanks(request):
    if 'user_id' not in request.session:
        return HttpResponseRedirect(reverse('dc:error'))

    user_id = request.session.get('user_id')
    print('user_id={}'.format(user_id))
    p = get_object_or_404(Participant, pk=request.session['user_id'])

    return render(request, 'dc/thanks.html', {"first_name": p.first_name})

dc/templates/dc/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Data Collection</title>
    <!-- TODO: name -->

    {% load staticfiles %}

    <link href="{% static 'dc/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'dc/css/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'dc/css/styles.css' %}" rel="stylesheet">

    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>-->
    <script src="{% static 'dc/js/jquery.min.js' %}"></script>
    <script src="{% static 'dc/dist/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'dc/js/jquery.floatThead.min.js' %}"></script>

    <script src="{% static 'dc/js/angular.min.js' %}"></script>
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Concept mapping of ‘exploitation of migrants working in low-skilled jobs’</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">

            </ul>
        </div>
        <!--<div id="navbar" class="navbar-collapse collapse">-->
        <!--<ul class="nav navbar-nav navbar-right">-->
        <!--<li><a href="#">Dashboard</a></li>-->
        <!--<li><a href="#">Settings</a></li>-->
        <!--<li><a href="#">Profile</a></li>-->
        <!--<li><a href="#">Help</a></li>-->
        <!--</ul>-->
        <!--<form class="navbar-form navbar-right">-->
        <!--<input type="text" class="form-control" placeholder="Search...">-->
        <!--</form>-->
        <!--</div>-->
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar" id="sidebar">
                <li id="welcome" class="disabled"><a href="{% url 'dc:welcome' %}">Welcome</a></li>
                <li id="sign_in" class="disabled"><a href="{% url 'dc:sign_in' %}">Sign Up</a></li>
                <li id="brainstorm" class="disabled"><a href="{% url 'dc:brainstorm' %}">Brainstorming</a></li>
                <li id="group" class="disabled"><a href="{% url 'dc:group_statements' %}">Sorting Statements</a></li>
                <li id="rate" class="disabled"><a href="{% url 'dc:rate_statements' %}">Rating Statements</a></li>
                <li id="thanks" class="disabled"><a>Thank you</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>

<script>
    $('body').on('click', 'li.disabled', function(event) {
        event.preventDefault();
    });
</script>

</body>
</html>

dc/templates/dc/brainstorm.html
{% extends "dc/base.html" %}

{% block content %}

{{ heading }}

<script>
    document.getElementById('brainstorm').className = "active";
</script>


<div ng-app="brainstormingApp" ng-controller="brainstormingController" id="ngDiv">

<form action="{% url 'dc:brainstorm' %}" method="post">
    {% csrf_token %}
    <fieldset>
    <div class="form-group" id="form_inputs" ng-repeat="statementInput in statements" set-focus="$last">
        <input class="form-control" type="text" name="statement" ng-keypress="onEnter($event)">
    </div>
    </fieldset>

    <div class="form-group form-actions">
        <input id="add_button"     tabindex="2" type="button" class="btn btn-primary" ng-click="addGroup()" value="Add Statement" />
        <input id="submit_button"  tabindex="1" type="submit" class="btn" ng-click="submitGroup($event)" value="Submit" />
    </div>
</form>


<script>

var app = angular.module( "brainstormingApp", [] ).config(function($httpProvider) {
    $httpProvider.defaults.xsrfCookieName = 'csrftoken';
    $httpProvider.defaults.xsrfHeaderName = 'X-CSRFToken';
});

app.directive('setFocus', function(){
  return {
      scope: {setFocus: '='},
      link: function(scope, element){
            element[0].children[0].focus();
      }
  };
});

app.controller(
    "brainstormingController", [ '$scope', '$http', '$log',
    function( $scope, $http, $log ) {
        $scope.statements = [""];

        $scope.addGroup = function() {
            $scope.statements.push($scope.statements.length);

        }

        $scope.submitGroup = function(e) {
            console.log('submitting');

            if(!confirm('Have you checked that all statements you have generated covers all experiences of ‘exploitation of migrants working in low-skilled position’?')) {
                e.preventDefault();
            }
        }

        $scope.onEnter = function(keyEvent) {
            if (keyEvent.which === 13) {
                keyEvent.preventDefault();
                $scope.addGroup();
            }
        }
    }
]);

</script>
</div>
{% endblock %}

dc/templates/dc/error.html
{% extends "dc/base.html" %}

{% block content %}

<script>
        document.getElementById('thanks').className = "active";
</script>

<div>Unfortunately there was an error.</div><br/>

{%if error_message %}

<div>{{error_message}}</div>
{% endif %}

{% endblock %}

dc/templates/dc/group.html
{% extends "dc/base.html" %}
<!--<!DOCTYPE html>-->
<!--<html>-->
<!--<head>-->
<!--<meta charset="utf-8">-->
<!--<title>Data Collection</title>-->
<!--{% load staticfiles %}-->

<!--&lt;!&ndash; AngularJS &ndash;&gt;-->
<!--<script src="{% static 'dc/js/angular.min.js' %}"></script>-->

<!--&lt;!&ndash; Sortable.js &ndash;&gt;-->
<!--<script src="http://rubaxa.github.io/Sortable/Sortable.js"></script>-->
<!--&lt;!&ndash;<script src="{% static 'dc/js/Sortable.min.js' %}"></script>&ndash;&gt;-->
<!--<script src="{% static 'dc/js/ng-sortable.js' %}"></script>-->

<!--<link rel="stylesheet" href="{% static 'dc/css/styles.css' %}" type="text/css"/>-->
<!--</style>-->


{% block content %}


{{ heading }}
<br/>

<div ng-app="groupingApp" ng-controller="groupingController">
    <link rel="stylesheet" href="{% static 'dc/css/styles.css' %}" type="text/css"/>

    <script>
        document.getElementById('group').className = "active";
    </script>

    {% csrf_token %}
    <button id="add_group" class="btn" ng-click="addGroup()">Add Group</button>

    <div class="row groups">
        <div class="col-md-3">
            <div class="layer">
                <div class="layer title title-source">Statements to group</div>
                <ul id="source_group" class="block__list block__list_tags">
                    {% for statement in statements %}
                    <li id="{{statement.id}}">{{statement}}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>


        <div class="col-md-8 col-md-offset-1">
            <div id="destination_group">
                <div id="group-1" class="layer">
                    <div class="layer title">
                        <input type="text" value="Group 1" id="group-1_title">
                    </div>
                    <ul class="block__list block__list_tags">
                    </ul>
                </div>

                <div id="group-2" class="layer">
                    <div class="layer title">
                        <input type="text" value="Group 2" id="group-2_title">
                    </div>
                    <ul class="block__list block__list_tags">
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <button id="save_button" class="btn btn-primary" ng-click="saveOrdering()">Save</button>

    <script src="{% static 'dc/js/Sortable.min.js' %}"></script>
    <script src="{% static 'dc/js/ng-sortable.js' %}"></script>

    <script id="jsbin-javascript" src="{% static 'dc/js/group.js' %}"></script>
</div>
{% endblock %}

dc/templates/dc/log_in.html
{% extends "dc/base.html" %}

{% block content %}

<script>
    document.getElementById('log_in').className = "active";
</script>

<div>Welcome {{ name }}.</div><br/>

<form action="{% url 'dc:logout' %}" method="post">
    {% csrf_token %}
    <div class="form-actions">
        <button type="submit" class="btn btn-primary" >Log Out</button>
    </div>
</form>

{% endblock %}

dc/templates/dc/rate.html
{% extends "dc/base.html" %}

{% block content %}

{{ heading }}
<br>

<script>
    document.getElementById('rate').className = "active";

    function checkForm() {

        if($('.missing:checked').length != 0) {
            alert("It seems that at least one statement has not been rated. Could you rate the statement(s) where the ‘Missing’ option is selected, please?");
            return false;
        }


        if(confirm("Have you checked that the ratings you have proposed represent the relative importance you give to each statement?")) {
            return true;
        } else {
            return false;
        }
    }
</script>
<form name="ratingForm" action="{% url 'dc:rate_statements' %}" method="post">
    {% csrf_token %}

    <table id="rating_table">
        <thead>
        <tr>
            <th></th>
            <th>Relatively unimportant (1)</th>
            <th>Somewhat important (2)</th>
            <th>Moderately important (3)</th>
            <th>Very important (4)</th>
            <th>Extremely important (5)</th>
            <th>Missing</th>
        </tr>
        </thead>

        {% for s in statements %}
        <tr>
            <td>{{ s }}</td>
            <td><input type="radio" name="{{s.id}}" id="{{s.id}}-1" value="1" autocomplete="off"></td>
            <td><input type="radio" name="{{s.id}}" id="{{s.id}}-2" value="2" autocomplete="off"></td>
            <td><input type="radio" name="{{s.id}}" id="{{s.id}}-3" value="3" autocomplete="off"></td>
            <td><input type="radio" name="{{s.id}}" id="{{s.id}}-4" value="4" autocomplete="off"></td>
            <td><input type="radio" name="{{s.id}}" id="{{s.id}}-5" value="5" autocomplete="off"></td>
            <td><input type="radio" name="{{s.id}}" class="missing" id="{{s.id}}-missing" autocomplete="off" checked></td>
        </tr>
        {% if forloop.counter|divisibleby:10 %}
        <tr>
            <td></td>
        </tr>
        {% endif %}
        {% endfor %}

    </table>

    <input type="submit" class="btn btn-primary" value="Submit" onclick="return checkForm()"/>
</form>

<script>
    var t = $('#rating_table');
    t.floatThead({ 'top': 50 });
</script>

{% endblock %}

dc/templates/dc/sign_in.html
{% extends "dc/base.html" %}

{% block content %}
<script>
    document.getElementById('sign_in').className = "active";
</script>

<h1 class="page-header">Please Sign In</h1>

Welcome {{user.first_name}},<br>
<br>
Below are information we need to collect for our analysis. Your personal details (name and email) will only be accessed by the main investigator.
Only aggregated data enabling anonymity would be used in our analysis.<br>
Please, check the information included below, correct it if need be and fill in the empty fields.<br>
<br>
Thank you very much.<br>
<br>

<form action="{% url 'dc:sign_in' %}" class="form-horizontal form-group" method="post">
    {% csrf_token %}
    <fieldset>
        <!--<legend>{{ title }}</legend>-->
        {% for field in form %}
        {% if field.errors %}
        <div class="control-group error">
            <label class="control-label">{{ field.label }}</label>
            <div class="controls">{{ field }}
                        <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
            </div>
        </div>
        {% else %}
        <div class="control-group">
            <label class="control-label">{{ field.label }}</label>
            <div class="controls">{{ field }}
                {% if field.help_text %}
                <p class="help-inline"><small>{{ field.help_text }}</small></p>
                {% endif %}
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </fieldset>
    <br />
    <div class="form-actions">
        <button type="submit" class="btn btn-primary" >Submit</button>
    </div>
</form>
{% endblock %}

dc/templates/dc/thanks.html
{% extends "dc/base.html" %}

{% block content %}

<script>
        document.getElementById('thanks').className = "active";
    </script>

Thank you very much for your contribution, {{first_name}}!<br>
The main investigator will contact you shortly to inform you about the next step. <br>
<br>
<i> Should you need any assistance in the meantime, please do not hesitate to contact the main investigator: <a href="mailto:sabah.boufkhed@lshtm.ac.uk">sabah.boufkhed@lshtm.ac.uk</a>.</i>


{% endblock %}

dc/templates/dc/welcome.html
{% extends "dc/base.html" %}

{% block content %}
<script>
    document.getElementById('welcome').className = "active";

    function EnableSubmit(val) {
        var submit = document.getElementById('submit_button');
        submit.disabled = !val.checked;
    }
</script>

{{ heading }}
<br/>

{%if error_message %}
<div>{{ error_message }}</div>
{% endif %}

<br/>

{% if user %}
<div>Welcome {{ user.first_name }}. Please log in with the provided password.</div>

<br/>

<form action="{% url 'dc:welcome_with_id' user_id=user.id %}" method="POST">
    {% csrf_token %}
    <label>Password:<input type="password" name="password" /></label>
    <div class="checkbox">
        <label><input type="checkbox" name="consent_checkbox" onchange="EnableSubmit(this)" />I agree</label>
    </div>
    <div class="checkbox">
        <label><input type="checkbox" name="no_consent_checkbox" onchange="alert('We understand that you are not interested anymore in participating in our research. Thank you very much for your interest and time.') " />I do not agree</label>
    </div>
    <button type="submit" id="submit_button" disabled="true" class="btn btn-primary">Go</button>
</form>


{% endif %}
{% endblock %}